spring.application.name=backend

spring.datasource.url = jdbc:mysql://root:vZIUcMDhxBACAdsdCZbdlXciksJcUWuu@tramway.proxy.rlwy.net:11889/railway
spring.datasource.username = root
spring.datasource.password = vZIUcMDhxBACAdsdCZbdlXciksJcUWuu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

server.port = 8080
